#
#    Copyright 2017 Information Control Company
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License atd
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3.4"
services:
  jenkins:
    image: dju-jenkins
    build:
      context: jenkins
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    shm_size: 2G
    volumes:
      -   dju_jenkins_home:/var/jenkins_home
      - type: bind
        source: ..
        target: /usr/demo
    ports:
      - "8085:8080"
  ucd-server:
    image: dju-ucd
    build:
      context: ucd-server
    ports:
      - "8446:8443"
      - "7918:7918"
      - "8086:8080"
  dev-server:
    image: dju-tomcat-agent
    build:
      context: tomcat-agent
    ports:
      - "8087:8080"
    environment:
      - AGENT_NAME=dev-server
  test-server:
    image: dju-tomcat-agent
    build:
      context: tomcat-agent
    ports:
      - "8088:8080"
    environment:
      - AGENT_NAME=test-server
  gem-server:
    image: spoonest/geminabox
    ports:
      - "9292:9292"
    volumes:
      - dju_geminabox_gems:/webapps/geminabox/data
    environment:
      - PRIVATE=true
      - USERNAME=gem
      - PASSWORD=gem
#      - RUBYGEMS_PROXY=true

volumes:
  dju_jenkins_home:
  dju_geminabox_gems:    
